project:
  type: website

# accessibility-focused syntax highlighting theme for code. 
# alternatives: github, monokai, dracula
highlight-style: a11y

website:
  title: "EMPLANT course"
  navbar:
    background: primary
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/amrei-bp/emplant_bioinformatics_course
          - text: Report a Bug
            href:  https://github.com/amrei-bp/emplant_bioinformatics_course/issues
    left:
      - href: data_management.qmd
        text: Reproducibility
      - href: qc.qmd
        text: Quality control
  search: 
    location: navbar
    type: textbox

  sidebar:
    style: "docked"
    search: true
    logo: figures/logo/SLUBI_logo.png
    contents:
      - text: "About the course"
        href: index.qmd
      - text: "Reproducibility"
        href: data_management.qmd
      - text: "Quality control"
        href: qc.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

  closeread-html:
    theme: yeti
    css: styles.css
    toc: true

execute:
  freeze: auto


